server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.132:3306/gmall_product?useUnicode=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.136.132
    port: 6379
#    password: <PASSWORD>
    database: 0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  rabbitmq:
    host: 192.168.136.132
    port: 5672
    username: guest
    password: guest